version: '3.7'
services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  redis_db:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
